#!/bin/bash

# Install dependencies
apt-get install -y python-apt git

# Create DIR
rm -rf /opt/arke
mkdir /opt/arke
cd /opt/arke

# Pull in
git clone git://github.com/keiouu/Arke.git .

# Ensure arke.py has exec permissions
chmod 0700 arke.py

# Setup config
cp /opt/arke/arke_config_example.py /opt/arke/arke_config.py
vi /opt/arke/arke_config.py

# Add cron
echo "Arke setup complete!"
echo "Add the following line to root crontab:"
echo "0 0 * * * /opt/arke/arke.py"
